driver:
  name: docker

platforms:
  - name: centos-7
    driver_config:
      image: corux/centos7-salt
      cap_add:
        - SYS_ADMIN
      run_command: /usr/sbin/init

provisioner:
  name: salt_solo
  formula: ttrss
  vendor_path: srv/salt
  pillars-from-files:
    ttrss.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - ttrss
  state_top:
    base:
      "*":
        - ttrss
        - ttrss.apache
        - ttrss.plugins

suites:
  - name: default
